# Generated by Django 4.0 on 2024-03-07 10:52

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('test_name', models.CharField(help_text='Please Enter the TestCase Name', max_length=255, verbose_name='Test Report Name')),
                ('jira_id', models.IntegerField(help_text='Jira Id', unique=True, verbose_name='Jira Id')),
                ('jira_summary', models.TextField(verbose_name='Jira Summary')),
                ('test_description', models.TextField(verbose_name='Test description')),
            ],
            options={
                'verbose_name': 'TestCase',
                'verbose_name_plural': 'TestCases',
            },
        ),
        migrations.CreateModel(
            name='TestCaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('step_id', models.IntegerField(verbose_name='step number')),
                ('step_data', models.TextField(verbose_name='Testing Parameters')),
                ('step_description', models.TextField()),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcase_app.testcasemodel')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
