# Generated by Django 4.0 on 2024-03-09 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testcase_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasestep',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_steps', to='testcase_app.testcasemodel'),
        ),
    ]
