# Generated by Django 4.0 on 2024-03-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with this EmailId already Exists'}, help_text='Required a Valid EmailAddress', max_length=200, unique=True, verbose_name='email address'),
        ),
    ]
